/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/tooth.glb --transform --simplify 
Files: public/tooth.glb [241.8KB] > C:\Users\Chirantan\Documents\Projects\truesmile\tooth-transformed.glb [206.47KB] (15%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tooth-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.material.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/tooth-transformed.glb')
